services:
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # AMQP (para los microservicios)
      - "15672:15672" # UI de administración
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  cartmanager:
    image: registry.gitlab.com/mauro4622412/microservice-grupo5/cart-manager:latest
    container_name: cartmanager
    ports:
      - "8083:8083"
    depends_on:
      - rabbitmq
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq

  usermanager:
    image: registry.gitlab.com/mauro4622412/microservice-grupo5/user-manager:latest
    container_name: usermanager
    ports:
      - "8081:8081"

  productmanager:
    image: registry.gitlab.com/mauro4622412/microservice-grupo5/product-manager:latest
    container_name: productmanager
    ports:
      - "8082:8082"
    depends_on:
      - rabbitmq
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq

  walletmanager:
    image: registry.gitlab.com/mauro4622412/microservice-grupo5/wallet-manager:latest
    container_name: walletmanager
    ports:
      - "8085:8085"
    depends_on:
      - rabbitmq
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
