services:
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # AMQP (para los microservicios)
      - "15672:15672" # UI de administración
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  cartmanager:
    image: ghcr.io/nachoeg/pas-cart-manager:latest
    container_name: cartmanager
    ports:
      - "8083:8083"
    depends_on:
      - rabbitmq
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq

  usermanager:
    image: ghcr.io/nachoeg/pas-user-manager:latest
    container_name: usermanager
    ports:
      - "8081:8081"

  productmanager:
    image: ghcr.io/nachoeg/pas-product-manager:latest
    container_name: productmanager
    ports:
      - "8082:8082"
    depends_on:
      - rabbitmq
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq

  walletmanager:
    image: ghcr.io/nachoeg/pas-wallet-manager:latest
    container_name: walletmanager
    ports:
      - "8085:8085"
    depends_on:
      - rabbitmq
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq

  deliveryordermanager:
    image: ghcr.io/nachoeg/pas-deliveryorder-manager:latest
    container_name: deliveryordermanager
    ports:
      - "8084:8084"
    depends_on:
      - rabbitmq
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
